In [1]:
import torch 
import torchvision.datasets as datasets
import os 
from torch.utils.data import WeightedRandomSampler, DataLoader
import torchvision.transforms as transforms
import torch.nn as nn

In [ ]:
loss_fn = nn.CrossEntropyLoss(weight=torch.tensor([1,50]))

In [15]:
def get_loader(root_dir, batch_size):
    my_transforms = transforms.Compose(
        [
            transforms.Resize((224,224)),
            transforms.ToTensor(),
        ]
    )
    
    dataset = datasets.ImageFolder(root=root_dir, transform=my_transforms)
    class_weights = []
    for root, subdir, files in os.walk(root_dir):
        if(len(files)) > 0:
            class_weights.append(1/len(files))
    sample_weights = [0]*len(dataset)
    
    for idx, (data, label) in enumerate(dataset):
        class_weight = class_weights[label]
        sample_weights[idx] = class_weight
        
    sampler = WeightedRandomSampler(sample_weights, num_samples=len(sample_weights), replacement=True)
    
    loader = DataLoader(dataset=dataset, batch_size=batch_size, sampler=sampler)
    
    return loader

__folder_path structure__  
    
Main Folder ("folder_path")  
|-Class 1  
|-Class 2  
|-Class 3  
|-  __...__  

In [16]:
def main():
    loader = get_loader(root_dir="folder_path", batch_size=8)
    for data, label in loader:
        print(label)

In [17]:
if __name__ == "__main__":
    main()

tensor([0, 1, 0, 1, 1, 0, 0, 0])
tensor([0, 0, 0, 0, 0, 0, 1, 0])
tensor([1, 1, 1, 0, 1, 0, 1, 0])
tensor([1, 1, 1, 1, 0, 0, 0, 0])
tensor([0, 1, 1, 0, 1, 0, 1, 1])
tensor([1, 1, 0, 1, 0, 0, 1, 0])
tensor([0, 0, 0, 0, 0, 0, 1, 0])
tensor([1, 0, 1, 1])
