In [2]:
import torch
import numpy as np

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [9]:
a = torch.tensor([[0,1,2],[3,4,5]], dtype=torch.float, device=device, requires_grad=True)
print(a, a.device, a.dtype, a.requires_grad, sep='\n')

tensor([[0., 1., 2.],
        [3., 4., 5.]], device='cuda:0', requires_grad=True)
cuda:0
torch.float32
True


In [11]:
x1 = torch.empty(size=(3,3))
x1

tensor([[-5.2497e+24,  3.0802e-41, -5.3079e+24],
        [ 3.0802e-41,  1.1210e-43,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00, -5.2479e+24]])

In [13]:
x2 = torch.zeros(size=(3,3))
x2

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
x3 = torch.ones(size=(3,3))
x3

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x4 = torch.eye(5,7)
x4

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.]])

In [23]:
x5 = torch.arange(start=0,end=10,step=2)
x5

tensor([0, 2, 4, 6, 8])

In [27]:
x6 = torch.linspace(start=0,end=0.2,steps=8)
x6

tensor([0.0000, 0.0286, 0.0571, 0.0857, 0.1143, 0.1429, 0.1714, 0.2000])

In [77]:
x7 = torch.empty(size=(2,10)).normal_(mean=4,std=2)
x7.mean(),x7.std(),x7

(tensor(3.4844),
 tensor(1.8750),
 tensor([[ 5.1949,  3.9541,  4.6724,  3.3953,  3.5348,  5.1958,  3.7845,  3.8603,
           2.9479,  3.4566],
         [ 1.5533,  0.1618,  5.1379,  0.5448, -0.0188,  6.5393,  2.4706,  4.5860,
           6.2634,  2.4520]]))

In [79]:
x8 = torch.empty(size=(2,10)).uniform_(-2,2)
x8

tensor([[ 1.9898,  0.9923,  0.0029, -1.9842, -0.9551, -1.6242,  0.8517, -0.0054,
         -0.3363,  0.2630],
        [-1.4080,  1.6032, -1.9522,  0.2635,  1.3755,  0.1874,  0.2651,  0.2148,
         -0.2131,  0.9982]])

In [65]:
x9 = torch.diag(torch.randn(3).normal_(mean=10,std=2))
x9

tensor([[ 7.2686,  0.0000,  0.0000],
        [ 0.0000,  7.9346,  0.0000],
        [ 0.0000,  0.0000, 14.2277]])

In [85]:
tensor = torch.arange(0,4)
tensor.bool(), tensor.short(), tensor.long(), tensor.half(), tensor.float(), tensor.double(), tensor

(tensor([False,  True,  True,  True]),
 tensor([0, 1, 2, 3], dtype=torch.int16),
 tensor([0, 1, 2, 3]),
 tensor([0., 1., 2., 3.], dtype=torch.float16),
 tensor([0., 1., 2., 3.]),
 tensor([0., 1., 2., 3.], dtype=torch.float64),
 tensor([0, 1, 2, 3]))

In [91]:
numpy_array = np.zeros((5,5))
tensor = torch.from_numpy(numpy_array)
print(tensor)
back_to_numpy = tensor.numpy()
print(back_to_numpy)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [130]:
x = torch.tensor([1,2,3,4,5])
x1 = x
y = torch.tensor([3,6,3,6,7])
y1 = y
A = torch.tensor(10)
z1 = torch.empty(5)

torch.add(x,y,out=z1)
z2 = x+y
z3 = x-y
x1.add_(y1)
x1.pow_(2)
z4 = torch.true_divide(x,y)
z5 = torch.divide(x,y)
z6 = torch.true_divide(x,A)
z7 = torch.divide(x,A)
z1, z2, z3, x1, z4, z5, z6, z7

(tensor([ 4.,  8.,  6., 10., 12.]),
 tensor([ 4,  8,  6, 10, 12]),
 tensor([-2, -4,  0, -2, -2]),
 tensor([ 16,  64,  36, 100, 144]),
 tensor([ 5.3333, 10.6667, 12.0000, 16.6667, 20.5714]),
 tensor([ 5.3333, 10.6667, 12.0000, 16.6667, 20.5714]),
 tensor([ 1.6000,  6.4000,  3.6000, 10.0000, 14.4000]),
 tensor([ 1.6000,  6.4000,  3.6000, 10.0000, 14.4000]))

In [134]:
a = torch.randn((3,16))
b = torch.randn((16,4))
d = torch.mm(a,b)
c = a.mm(b)
c, d

(tensor([[ 6.9678,  0.6362, -0.1467,  1.8451],
         [-3.0308, -0.5298, -0.4531,  0.3389],
         [ 3.3651, -0.5659,  6.5067, -1.2111]]),
 tensor([[ 6.9678,  0.6362, -0.1467,  1.8451],
         [-3.0308, -0.5298, -0.4531,  0.3389],
         [ 3.3651, -0.5659,  6.5067, -1.2111]]))

In [153]:
a = torch.tensor([[1,3],[2,4]], dtype=torch.float)
print(a)
b = a.matrix_power(2)
print(b)
c = a.matrix_exp()
print(c)

tensor([[1., 3.],
        [2., 4.]])
tensor([[ 7., 15.],
        [10., 22.]])
tensor([[ 51.9690, 112.1049],
        [ 74.7366, 164.0738]])


In [157]:
x = torch.randn([1,2,3,4,5])
y = torch.randn([3,6,3,6,7])
z1 = x*y
z2 = torch.dot(x,y)
z1, z2

(tensor([ 3, 12,  9, 24, 35]), tensor(83))

In [171]:
batch1 = 3
batch2 = 2
m = 2
n = 2
p = 1
x = torch.randn(batch2, n, m)
y = torch.randn(batch2, m , p)
z1 = torch.bmm(x,y)
x,y,z1

(tensor([[[ 1.6785, -0.4026],
          [-0.4200,  1.3686]],
 
         [[ 0.3584,  1.4335],
          [ 0.0553,  0.9756]]]),
 tensor([[[-0.1553],
          [ 1.4523]],
 
         [[ 0.8627],
          [-0.1188]]]),
 tensor([[[-0.8454],
          [ 2.0528]],
 
         [[ 0.1389],
          [-0.0682]]]))

In [179]:
x = torch.randn((3,4,2))
max_x, indices = torch.max(x, dim=1)
max_x, x

(tensor([[1.2323, 2.0074],
         [1.4471, 0.2048],
         [0.8248, 0.6606]]),
 tensor([[[-0.3650,  0.1911],
          [-0.0341, -1.4536],
          [ 1.2323,  2.0074],
          [ 1.2257,  1.1025]],
 
         [[ 1.4471,  0.2048],
          [ 0.4788, -0.0171],
          [-0.5719, -0.8111],
          [ 0.0482, -2.0185]],
 
         [[-0.0669,  0.4838],
          [ 0.8248,  0.6606],
          [-0.0915, -0.7101],
          [-1.1340,  0.5211]]]))

In [183]:
a = torch.tensor([1,2,3,4,5])
b = torch.tensor([1,2,3,2,1])
c = torch.randn(2,3)
z1 = torch.eq(a,b)
z2 = torch.sort(c,dim=0)

z1, c, z2

(tensor([ True,  True,  True, False, False]),
 tensor([[ 0.1643, -0.5347, -0.6297],
         [ 0.1122, -0.1343, -0.2701]]),
 torch.return_types.sort(
 values=tensor([[ 0.1122, -0.5347, -0.6297],
         [ 0.1643, -0.1343, -0.2701]]),
 indices=tensor([[1, 0, 0],
         [0, 1, 1]])))

In [190]:
x = torch.empty(size=(1,20)).uniform_(0,40)
z = torch.clamp(x,min=10,max=25)
x, z

(tensor([[38.3476, 17.6010, 37.2080, 39.8673,  2.6227, 39.6498, 29.0317, 17.4265,
          32.8501,  7.7630, 34.6245, 22.9619, 19.6199,  4.7261, 26.2702, 22.6355,
          26.6715, 24.9266, 31.2643, 35.6506]]),
 tensor([[25.0000, 17.6010, 25.0000, 25.0000, 10.0000, 25.0000, 25.0000, 17.4265,
          25.0000, 10.0000, 25.0000, 22.9619, 19.6199, 10.0000, 25.0000, 22.6355,
          25.0000, 24.9266, 25.0000, 25.0000]]))

In [20]:
x = torch.arange(10)
y = torch.rand((3,5))
rows = [1,0]
cols = [4,0]
z = x.numpy()
z1 = x[((x<2) | (x>8))]
z2 = torch.where(x>5, x, 2*x)
z3 = x.view((2,5))
x,x.numel(),x.ndimension(),y,y.numel(),y.ndimension(),y[rows,cols],z1,z2,z3
# z[np.any(rows,cols)]

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 10,
 1,
 tensor([[0.9883, 0.4946, 0.6999, 0.8055, 0.5054],
         [0.8765, 0.2010, 0.0027, 0.7742, 0.1388],
         [0.9459, 0.2090, 0.0175, 0.8527, 0.7494]]),
 15,
 2,
 tensor([0.1388, 0.9883]),
 tensor([0, 1, 9]),
 tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9]),
 tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]))

In [24]:
x = torch.rand((2,5))
y = torch.rand((2,5))
z = torch.cat((x,y),axis=0)
z,z.reshape(-1)

(tensor([[0.2295, 0.5681, 0.8896, 0.9418, 0.3453],
         [0.9747, 0.5610, 0.4171, 0.4060, 0.2502],
         [0.0530, 0.9014, 0.8807, 0.2543, 0.6607],
         [0.8497, 0.6310, 0.4793, 0.2032, 0.9390]]),
 tensor([0.2295, 0.5681, 0.8896, 0.9418, 0.3453, 0.9747, 0.5610, 0.4171, 0.4060,
         0.2502, 0.0530, 0.9014, 0.8807, 0.2543, 0.6607, 0.8497, 0.6310, 0.4793,
         0.2032, 0.9390]))

In [32]:
x = torch.randn(2, 3, 1, 5, 1)
z1 = x.permute((2, 3, 4, 0, 1))

z1, z1.unsqueeze(5), 

(tensor([[[[[ 1.0237e+00, -3.4193e-01, -6.9026e-04],
            [-1.7952e+00,  2.3419e+00, -9.6733e-03]]],
 
 
          [[[-2.2300e-01, -9.5874e-01, -5.3788e-01],
            [ 1.0572e-01, -4.3133e-01, -1.4302e+00]]],
 
 
          [[[ 1.3937e+00,  1.6984e+00, -1.6677e+00],
            [-1.0845e-01, -1.2998e+00, -7.4809e-01]]],
 
 
          [[[-9.7731e-01, -8.0692e-01, -6.1020e-01],
            [-2.6809e-01,  5.8946e-01,  6.0344e-01]]],
 
 
          [[[-4.2582e-01,  1.3561e-01, -3.2289e-02],
            [-1.5078e-01,  1.5257e+00, -5.4632e-01]]]]]),
 tensor([[[[[[ 1.0237e+00],
             [-3.4193e-01],
             [-6.9026e-04]],
 
            [[-1.7952e+00],
             [ 2.3419e+00],
             [-9.6733e-03]]]],
 
 
 
          [[[[-2.2300e-01],
             [-9.5874e-01],
             [-5.3788e-01]],
 
            [[ 1.0572e-01],
             [-4.3133e-01],
             [-1.4302e+00]]]],
 
 
 
          [[[[ 1.3937e+00],
             [ 1.6984e+00],
             [-1.6677e+00

In [ ]:
x